import { GearItem } from "@/lib/types";

export const mockItems: GearItem[] = [
  { id: "1", title: "NVIDIA RTX 3070", category: "GPU", brand: "NVIDIA", model: "RTX 3070 Founders Edition", price: 280, condition: "Good", status: "Available", sellerName: "Alex Kim", contactMethod: "alex.kim@internal.example", description: "Great 1440p gaming GPU, recently cleaned and repasted.", knownIssues: "Minor cosmetic scratches on backplate.", pickupMethod: "Office pickup - Building A lobby", imageUrls: ["https://images.unsplash.com/photo-1591488320449-011701bb6704?auto=format&fit=crop&w=1200&q=80","https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=1200&q=80"], createdAt: "2026-04-29" },
  { id: "2", title: "Keychron K8 Mechanical Keyboard", category: "Keyboard", brand: "Keychron", model: "K8 Hot-Swappable", price: 55, condition: "Like New", status: "Reserved", sellerName: "Priya Shah", contactMethod: "Slack: @priya", description: "Wireless TKL keyboard with Gateron Brown switches.", knownIssues: "No issues.", pickupMethod: "Meet in cafeteria at lunch", imageUrls: ["https://images.unsplash.com/photo-1511467687858-23d96c32e4ae?auto=format&fit=crop&w=1200&q=80"], createdAt: "2026-05-01" },
  { id: "3", title: "Samsung 1TB NVMe SSD", category: "SSD", brand: "Samsung", model: "970 EVO Plus 1TB", price: 60, condition: "Good", status: "Available", sellerName: "Jordan Lee", contactMethod: "jordan.lee@internal.example", description: "Fast PCIe SSD, used in secondary workstation.", knownIssues: "Drive health at 91%.", pickupMethod: "Shipping via internal mail", imageUrls: ["https://images.unsplash.com/photo-1591799264318-7e6ef8ddb7ea?auto=format&fit=crop&w=1200&q=80"], createdAt: "2026-05-03" },
  { id: "4", title: "Dell 27\" 4K Monitor", category: "Monitor", brand: "Dell", model: "U2720Q", price: 230, condition: "Fair", status: "Sold", sellerName: "Mina Park", contactMethod: "mina.park@internal.example", description: "Sharp color-accurate monitor, ideal for dev/design.", knownIssues: "One faint bright pixel near edge.", pickupMethod: "Office pickup - IT storage room", imageUrls: ["https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=1200&q=80"], createdAt: "2026-04-20" }
];

export const myMockItems: GearItem[] = mockItems.filter((item) => ["1", "3"].includes(item.id));
